# Generated by Django 2.1.5 on 2020-09-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200913_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='notMucVotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='theSkyeVotes',
            field=models.IntegerField(null=True),
        ),
    ]
