# Generated by Django 2.1.5 on 2020-09-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200913_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='notMucVotes',
            new_name='notMuchVotes',
        ),
    ]
