# Generated by Django 2.1.5 on 2020-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200913_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notMuchVotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='theSkyeVotes',
            field=models.IntegerField(null=True),
        ),
    ]
